import type { Metadata } from 'next';
import ToastProvider from '@/components/toast-provider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
