import ToastProvider from '@/components/toast-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
